<?php
/**
 * @file
 * Interface module for talking with the materials backend.
 */

// Load Field module hooks.
module_load_include('inc', 'ding_more_info', 'ding_more_info.field');

/**
 * Implements hook_entity_view().
 */
function ding_more_info_entity_view($entity, $type, $view_mode, $langcode) {
  $search_result = $type == 'ting_object' && $view_mode == 'search_result';
  $collection_view = $type == 'ting_object' && $view_mode == 'collection_list';

  if ($search_result) {
    $entity->content['#group_children']['ting_more_info'] = 'group_info';
  }
  elseif ($collection_view) {
    $entity->content['#group_children']['ting_more_info'] = 'group_info';
  }
}

/**
 * Implements hook_menu().
 */
function ding_more_info_menu() {
  $menu = array();

  $menu['admin/config/ding/moreinfo'] = array(
    'title' => 'More Info Button',
    'description' => 'Configure more info button placement',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_more_info_admin_form'),
    'access arguments' => array('configure more info'),
    'file' => 'ding_more_info.admin.inc',
  );

  return $menu;
}

/**
 * Implements hook_permission().
 */
function ding_more_info_permission() {
  $perm = array();

  $perm['configure more info'] = array(
    'title' => t('More info button'),
    'description' => t('Configure the placement of more info button.'),
  );

  return $perm;
}


