<?php

/**
 * @file
 * Install, update and uninstall functions for the ding_more_info.
 */

/**
 * Implements hook_ding_entity_fields().
 */
function ding_more_info_ding_entity_fields() {
  return array(
    'ting_more_info' => array(
      'field' => array(
        'locked' => TRUE,
        'storage' => array(
          'type' => 'virtual_field',
        ),
      ),
      'instance' => array(
        'label' => t('More info'),
      ),
    ),
  );
}
